/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __BT_STRING_DEFINE_H__
#define __BT_STRING_DEFINE_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Not included in excel file, but it exist in STMS */
#define BT_STR_ALLOW_TO_DELETE_YOUR_FILE_Q \
	_("IDS_BT_BODY_ALLOW_PS_TO_DELETE_YOUR_FILE_Q")
#define BT_STR_ALLOW_TO_GET_YOUR_FILE_Q \
	_("IDS_BT_BODY_ALLOW_PS_TO_GET_YOUR_FILE_Q")
#define BT_STR_ALLOW_TO_PUT_A_FILE_IN_Q \
	_("IDS_BT_BODY_ALLOW_PS_TO_PUT_A_FILE_IN_Q")
#define BT_STR_ALWAYS_ON _("IDS_BT_BODY_ALWAYS_ON")
#define BT_STR_CANCELLED _("IDS_BT_BODY_CANCELLED")
#define BT_STR_CONTACT_ALREADY_EXISTS \
	_("IDS_BT_BODY_CONTACT_ALREADY_EXISTS")
#define BT_STR_FILE_SENT _("IDS_BT_BODY_FILE_SENT")
#define BT_STR_HEADSET _("IDS_BT_BODY_HEADSET")
#define BT_STR_INVALID_TIME_ENTER_NUMBER_BETWEEN_1_AND_60 \
	_("IDS_BT_BODY_INVALID_TIME_ENTER_NUMBER_BETWEEN_1_AND_60")
#define BT_STR_MINUTE _("IDS_BT_BODY_MINUTE_LC")
#define BT_STR_MY_PHONES_NAME _("IDS_BT_BODY_MY_PHONES_NAME")
#define BT_STR_MY_PHONES_VISIBILITY _("IDS_BT_BODY_MY_PHONES_VISIBILITY")
#define BT_STR_NO_MORE_CONNECTIONS_POSSIBLE \
	_("IDS_BT_BODY_NO_MORE_CONNECTIONS_POSSIBLE_VODA")
#define BT_STR_PAIRED_DEVICES _("IDS_BT_BODY_PAIRED_DEVICES")
#define BT_STR_PRINTER _("IDS_BT_BODY_PRINTER")
#define BT_STR_RECEIVCED _("IDS_BT_BODY_RECEIVED")
#define BT_STR_SERVICES _("IDS_BT_BODY_SERVICES")
#define BT_STR_UPDATING _("IDS_BT_BODY_UPDATING_ING")
#define BT_STR_BLUETOOTH_DEVICES _("IDS_BT_HEADER_BLUETOOTH_DEVICES")
#define BT_STR_ENTER_PIN _("IDS_BT_HEADER_ENTERPIN")
#define BT_STR_NEW_DEVICE _("IDS_BT_HEADER_NEW_DEVICE")
#define BT_STR_PRINTING	 _("IDS_BT_HEADER_PRINTING")
#define BT_STR_CONNECT_STEREO _("IDS_BT_OPT_CONNECT_STEREO")
#define BT_STR_DOWNLOAD _("IDS_BT_OPT_DOWNLOAD")
#define BT_STR_PC _("IDS_BT_OPT_PC")
#define BT_STR_PRINT _("IDS_BT_OPT_PRINT")
#define BT_STR_SEARCH_OPTIONS _("IDS_BT_OPT_SEARCH_OPTIONS")
#define BT_STR_ALLOW_PS_TO_CONNECT_Q _("IDS_BT_POP_ALLOW_PS_TO_CONNECT_Q")
#define BT_STR_BLUETOOTH_ERROR_TRY_AGAIN_Q \
	_("IDS_BT_POP_BLUETOOTH_ERROR_TRY_AGAIN_Q")
#define BT_STR_BLUETOOTH_TIMEOUT_TRY_AGAIN_Q \
	_("IDS_BT_POP_BLUETOOTH_TIMEOUT_TRY_AGAIN_Q")
#define BT_STR_CONFIRM_PASSKEY_IS_PS_TO_PAIR_WITH_PS \
	_("IDS_BT_POP_CONFIRM_PASSKEY_IS_PS_TO_PAIR_WITH_PS")
#define BT_STR_UNABLE_TO_CONNECT_TRY_Q _("IDS_BT_POP_CONNECTAGAIN")
#define BT_STR_DELETE_QUESTION _("IDS_BT_POP_DELETE_Q")
#define BT_STR_DELETING _("IDS_BT_POP_DELETING_ING")
#define BT_STR_DEVICE_DELETED _("IDS_BT_POP_DEVICEDELETED")
#define BT_STR_DOWNLOADED _("IDS_BT_POP_DOWNLOADED")
#define BT_STR_DOWNLOADING_FAILED _("IDS_BT_POP_DOWNLOADING_FAILED")
#define BT_STR_DOWNLOADING _("IDS_BT_POP_DOWNLOADING_ING")
#define BT_STR_EMPTY_NAME _("IDS_BT_POP_EMPTY_NAME")
#define BT_STR_ENTER_NUMBER_BETWEEN_PD_AND_PD \
	_("IDS_BT_POP_ENTER_NUMBER_BETWEEN_PD_AND_PD")
#define BT_STR_INCORRECT_PIN_TRY_AGAIN_Q \
	_("IDS_BT_POP_INCORRECT_PIN_TRY_AGAIN_Q")
#define BT_STR_PD_FILES_RECEIVED _("IDS_BT_POP_PD_FILES_RECEIVED")
#define BT_STR_SENDING_CANCELLED _("IDS_BT_POP_SENDINGCANCEL")
#define BT_STR_UNABLE_TO_SEND _("IDS_BT_POP_SENDINGFAIL")
#define BT_STR_SERIAL_CONNECT_WITH_PS_Q _("IDS_BT_POP_SERIAL_CONNECT_WITH_PS_Q")
#define BT_STR_FILE_RECEIVED _("IDS_BT_POP_SUBFILERECEIVED")
#define BT_STR_UNABLE_TO_GET_SERVICE_LIST \
	_("IDS_BT_POP_UNABLE_TO_GET_SERVICE_LIST")
#define BT_STR_CONNECT _("IDS_BT_SK_CONNECT")
#define BT_STR_DISCONNECT _("IDS_BT_SK_DISCONNECT")
#define BT_STR_DOWNLOAD_CANCELLED _("IDS_BR_POP_DOWNLOAD_CANCELLED")
#define BT_STR_DELETE_FAILED _("IDS_COM_POP_DELETE_FAILED")
#define BT_STR_BLUETOOTH_ACTIVATED _("IDS_BT_POP_ACTIVATED")
#define BT_STR_BLUETOOTH_DEACTIVATED _("IDS_BT_POP_DEACTIVATED")
#define BT_STR_ACTIVATING_ING _("IDS_BT_BODY_TURNING_ON_BLUETOOTH_ING")
#define BT_STR_DEACTIVATING_ING _("IDS_BT_BODY_TURNING_OFF_BLUETOOTH_ING")
#define BT_STR_OPERATION_FAILED _("IDS_BT_BODY_OPERATION_FAILED")
#define BT_STR_SEARCHING _("IDS_BT_BODY_SEARCHINGDEVICE")
#define BT_STR_SEARCHING_STOPPED _("IDS_BT_BODY_SEARCHING_STOPPED")
#define BT_STR_DISCONNECTING_FAILED _("IDS_WIFI_POP_DISCONNECTING_FAILED")
#define BT_STR_FILE_OVERWITE_Q _("IDS_BT_POP_FILEOVERWRITEQUERY")
#define BT_STR_CONNECTED _("IDS_BT_POP_CONNECTED")
#define BT_STR_DEVICE_NAME _("IDS_BT_BODY_DEVICENAME")
#define BT_STR_NO_DEVICE _("IDS_BT_BODY_NO_DEVICES")
#define BT_STR_GETTING_SERVICE_LIST _("IDS_BT_POP_GETTINGSERVICELIST")
#define BT_STR_HEADSET_INFO _("IDS_BT_BODY_INFOHEADSET")
#define BT_STR_SELECTED _("IDS_BT_POP_SELECTED")
#define BT_STR_SELECT_DEVICES _("IDS_BT_HEADER_SELECT_DEVICE")

#define BT_STR_CONNECT_TO_DEVICE \
	_("IDS_BT_BODY_CONNECT_TO_BLUETOOTH_DEVICE")

#define BT_STR_UNABLE_TO_GET_THE_SERVICE_LIST \
	_("IDS_BT_POP_UNABLE_TO_GET_SERVICE_LIST")

#define BT_STR_FLIGHT_MODE \
	_("IDS_BT_POP_UNABLE_TO_ACTIVATE_BLUETOOTH_WHEN_FLIGHT_MODE_IS_ON")

#define BT_STR_CONNECTED_PHONE_AND_MEDIO_AUDIO \
	_("IDS_BT_BODY_CONNECTED_TO_PHONE_AND_MEDIA_AUDIO")

#define BT_STR_CONNECTED_PHONE_AUDIO \
	_("IDS_BT_BODY_CONNECTED_TO_PHONE_AUDIO")

#define BT_STR_CONNECTED_MEDIA_AUDIO \
	_("IDS_BT_BODY_CONNECTED_TO_MEDIA_AUDIO")

#define BT_STR_CONNECTED_HID_DEVICE \
	_("IDS_BT_POP_CONNECTED_TO_HID_DEVICE")

#define BT_STR_SCANNING \
	_("IDS_BT_BODY_SCANNING_ING")

#define BT_STR_SCAN \
	_("IDS_BT_SK_SCAN")


#define BT_STR_SVC_HEADSET  _("IDS_BT_BODY_HEADSET")
#define BT_STR_SVC_HEADSET_D _("IDS_BT_BODY_INFOHEADSET")

#define BT_STR_SVC_HF  _("IDS_BT_BODY_HANDSFREE")
#define BT_STR_SVC_HF_D _("IDS_BT_BODY_INFOHANDSFREE")

#define BT_STR_SVC_STEREO  _("IDS_BT_OPT_STEREO_HEADSET")
#define BT_STR_SVC_STEREO_D _("IDS_BT_BODY_INFOAVHEADSET")

#define BT_STR_SVC_FT  _("IDS_BT_BODY_FILE_TRANSFER")
#define BT_STR_SVC_FT_D _("IDS_BT_BODY_INFOFILETRANSFER")

#define BT_STR_SVC_OP  _("IDS_BT_BODY_OBJECT_PUSH")
#define BT_STR_SVC_OP_D _("IDS_BT_BODY_INFOOBJECTPUSH")

#define BT_STR_SVC_BPP  _("IDS_BT_BODY_BASIC_PRINTING")
#define BT_STR_SVC_BPP_D  _("IDS_BT_BODY_PRINTER_SERVICEINFO")

#define BT_STR_SVC_DUN  _("IDS_BT_BODY_DIAL_UP_NETWORKING")
#define BT_STR_SVC_DUN_D _("IDS_BT_BODY_INFODIALUP")

#define BT_STR_SVC_HID  _("IDS_BT_POP_HID_DEVICE")
#define BT_STR_SVC_HID_D _("IDS_BT_BODY_HID_HKEYBOARD_MOUSE_ETC")

#define BT_STR_SVC_SPP _("IDS_BT_BODY_SERIAL_PORT")

#define BT_STR_SVC_SPP_D  \
	_("IDS_BT_BODY_THIS_IS_USED_TO_CONNECT_TO_OTHER_BLUETOOTH_DEVICES_VIA_A_VIRTUAL_SERIAL_PORT")

#define BT_STR_CONNECTION_EXISTS \
	_("IDS_BT_POP_FAILED_TO_CONNECT_HEADSET_OTHER_DEVICE_REFUSED_CONNECTION")

#define BT_STR_VISIBLE _("IDS_BT_BODY_VISIBLE")
#define BT_STR_TWO_MINUTES _("IDS_BT_BODY_2_MINUTES")
#define BT_STR_UNPAIR _("IDS_BT_OPT_UNPAIR")
#define BT_STR_CONNECTION_OPTIONS _("IDS_BT_BODY_CONNECTION_OPTIONS")
#define BT_STR_CALL_AUDIO _("IDS_BT_BODY_CALL_AUDIO")
#define BT_STR_MEDIA_AUDIO _("IDS_BT_BODY_MEDIA_AUDIO")
#define BT_STR_PS_REMAINING _("IDS_BT_BODY_PS_REMAINING")
#define BT_STR_TAP_TO_CONNECT _("IDS_BT_BODY_TAP_TO_CONNECT")
#define BT_STR_TAP_TO_DISCONNECT _("IDS_BT_BODY_TAP_TO_DISCONNECT")
#define BT_STR_AVAILABLE_DEVICES _("IDS_BT_BODY_AVAILABLE_DEVICES")
#define BT_STR_FIVE_MINUTES _("IDS_BT_BODY_5_MINUTES")
#define BT_STR_ONE_HOUR _("IDS_BT_BODY_1_HOUR")
#define BT_STR_DISCONNECTING _("IDS_BT_BODY_DISCONNECTING")
#define BT_STR_END_CONNECTION _("IDS_BT_POP_THIS_WILL_END_YOUR_CONNECTION_WITH")
#define BT_STR_DISCONNECT_Q _("IDS_BT_POP_DISCONNECT")
#define BT_STR_DETAILS _("IDS_BT_BODY_DETAILS")
#define BT_STR_INPUT_DEVICE _("IDS_BT_BODY_INPUT_DEVICE")
#define BT_STR_NO_DEVICE_FOUND _("IDS_BT_BODY_NO_BLUETOOTH_DEVICE_FOUND")
#define BT_STR_PAIRED _("IDS_BT_BODY_PAIRED")
#define BT_STR_SEARCHING_SERVICES _("IDS_BT_POP_SEARCHING_SERVICES_ING")

/* System string */
#define BT_STR_SEARCH dgettext("sys_string", "IDS_COM_SK_SEARCH")
#define BT_STR_STOP dgettext("sys_string", "IDS_COM_SK_STOP")
#define BT_STR_DONE dgettext("sys_string", "IDS_COM_SK_DONE")
#define BT_STR_OK dgettext("sys_string", "IDS_COM_SK_OK")
#define BT_STR_CANCEL dgettext("sys_string", "IDS_COM_SK_CANCEL")
#define BT_STR_RENAME dgettext("sys_string", "IDS_COM_SK_RENAME")
#define BT_STR_EDIT dgettext("sys_string", "IDS_COM_SK_EDIT")
#define BT_STR_QUIT dgettext("sys_string", "IDS_COM_SK_QUIT")
#define BT_STR_SAVE dgettext("sys_string", "IDS_COM_SK_SAVE")
#define BT_STR_YES dgettext("sys_string", "IDS_COM_SK_YES")
#define BT_STR_NO dgettext("sys_string", "IDS_COM_SK_NO")
#define BT_STR_DATE dgettext("sys_string", "IDS_BT_BODY_DATE")
#define BT_STR_DELETE dgettext("sys_string", "IDS_COM_BODY_DELETE")
#define BT_STR_DELETE_ALL dgettext("sys_string", "IDS_COM_BODY_DELETE_ALL")
#define BT_STR_BLUETOOTH dgettext("sys_string", "IDS_COM_BODY_BLUETOOTH")
#define BT_STR_BACK dgettext("sys_string", "IDS_COM_BODY_BACK")
#define BT_STR_SETTINGS dgettext("sys_string", "IDS_COM_BODY_SETTINGS")
#define BT_STR_NAME dgettext("sys_string", "IDS_COM_BODY_DETAILS_NAME")
#define BT_STR_SELECT_ALL dgettext("sys_string", "IDS_COM_BODY_SELECT_ALL")
#define BT_STR_LOW_BATTERY dgettext("sys_string", "IDS_COM_BODY_LOW_BATTERY")
#define BT_STR_HELP dgettext("sys_string", "IDS_COM_BODY_HELP")
#define BT_STR_CLOSE dgettext("sys_string", "IDS_COM_BODY_CLOSE")
#define BT_STR_CREATE_FOLDER \
	dgettext("sys_string", "IDS_COM_BODY_CREATE_FOLDER")
#define BT_STR_OFF dgettext("sys_string", "IDS_COM_BODY_OFF")
#define BT_STR_ALL dgettext("sys_string", "IDS_COM_BODY_ALL")
#define BT_STR_PHONE dgettext("sys_string", "IDS_COM_BODY_PHONE")
#define BT_STR_INFORMATION dgettext("sys_string", "IDS_COM_OPT_INFORMATION")
#define BT_STR_ERROR dgettext("sys_string", "IDS_COM_POP_ERROR")
#define BT_STR_DELETED dgettext("sys_string", "IDS_COM_POP_DELETED")
#define BT_STR_CONNECTION_FAILED \
	dgettext("sys_string", "IDS_COM_POP_CONNECTION_FAILED")
#define BT_STR_CONNECTING dgettext("sys_string", "IDS_COM_POP_CONNECTING")
#define BT_STR_NORMAL dgettext("sys_string", "IDS_IDLE_BODY_NORMAL")
#define BT_STR_BLUETOOTH_HELP dgettext("sys_string", "IDS_COM_BODY_HELP")
#define BT_STR_BLUETOOTH_CLOSE dgettext("sys_string", "IDS_COM_BODY_CLOSE")


/* Below needs to be added to PO files for use in bt-syspopup */
#define BT_STR_RECEIVE_PS_FROM_PS_Q _("IDS_BT_POP_RECEIVE_PS_FROM_PS_Q?")
#define BT_STR_OVERWRITE_FILE_Q _("IDS_BT_POP_PS_ALREADY_EXISTS_OVERWRITE_Q")
#define BT_STR_PASSKEY_MATCH_Q _("IDS_BT_POP_MATCH_PASSKEYS_ON_PS_Q?")
#define BT_STR_ENTER_PS_ON_PS_TO_PAIR \
	_("IDS_BT_BODY_ENTER_P1SS_ON_P2SS_TO_PAIR_THEN_TAP_RETURN_OR_ENTER")

#define BT_STR_EXCHANGE_OBJECT_WITH_PS_Q \
	_("IDS_BT_POP_EXCHANGEOBJECT")

#define BT_STR_BLUETOOTH_PAIRING_REQUEST \
	_("IDS_BT_HEADER_BLUETOOTH_PAIRING_REQUEST")

#define BT_STR_ENTER_PIN_TO_PAIR \
	_("IDS_BT_POP_CONFIRM_PASSKEY_IS_P2SS_TO_PAIR_WITH_P1SS")

#define BT_STR_SHOW_PASSWORD \
	_("IDS_BT_BODY_SHOW_PASSWORD")

#define BT_STR_CONFIRM_PASSKEY_PS_TO_PAIR_WITH_PS \
	_("IDS_BT_POP_CONFIRM_PASSKEY_IS_P2SS_TO_PAIR_WITH_P1SS")

/* Below needs to be added to PO files for use in bluetooth-share-ui */
#define BT_STR_SHARING_FN  _("IDS_BT_POP_SHARING_ING")

/* Below needs to be added to PO files for use in bluetooth-share */
#define BT_STR_FILE_EXSIST_MSG	_("IDS_BT_POP_PS_ALREADY_EXISTS_OVERWRITE_Q")
#define BT_STR_FILE_DELETE_AUTHORIZE_MSG	_("Delete %s by %s ?")
#define BT_STR_SENDING _("IDS_BT_POP_SENDING_ING")
#define BT_STR_RECEIVING _("IDS_BT_POP_RECEIVING")
#define BT_STR_MEMORY_FULL _("IDS_BT_POP_MEMORYFULL")

/* Below needs to be added to PO files for use in beat-bluetooth */
#define BT_STR_BLUETOOTH_ON		_("IDS_BT_POP_ACTIVATED")
#define BT_STR_BLUETOOTH_AVAILABLE	_("IDS_BT_BODY_BLUETOOTH_AVAILABLE")

#ifdef __cplusplus
}
#endif

#endif /* __BT_STRING_DEFINE_H__ */
